# Generated by Django 4.2.17 on 2025-06-26 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        ('inventory_item', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('transaction_date', models.DateField()),
                ('transaction_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_tax_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('total_discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vendor.vendor')),
            ],
            options={
                'verbose_name': 'Purchase Transaction',
                'verbose_name_plural': 'Purchase Transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseTransactionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True)),
                ('warranty_period_type', models.CharField(blank=True, choices=[('DAYS', 'Days'), ('MONTHS', 'Months'), ('YEARS', 'Years')], db_index=True, default='YEARS', help_text='Warranty period type', max_length=20, null=True)),
                ('warranty_period', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_line_items', to='inventory_item.inventoryitem')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_items', to='purchase.purchasetransaction')),
            ],
            options={
                'verbose_name': 'Purchase Transaction Item',
                'verbose_name_plural': 'Purchase Transaction Items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['serial_number'], name='purchases_p_serial__0416f1_idx'), models.Index(fields=['reference_number'], name='purchases_p_referen_58bcc0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='purchasetransaction',
            index=models.Index(fields=['transaction_date'], name='purchases_p_transac_3d55bc_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasetransaction',
            index=models.Index(fields=['transaction_id'], name='purchases_p_transac_6fac49_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasetransaction',
            index=models.Index(fields=['reference_number'], name='purchases_p_referen_b539d7_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasetransaction',
            index=models.Index(fields=['invoice_number'], name='purchases_p_invoice_8d604f_idx'),
        ),
    ]
