# Generated by Django 5.2.3 on 2025-06-27 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_item", "0003_update_foreignkey_to_lineitem"),
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="purchasetransaction",
            new_name="purchase_pu_transac_c23f4f_idx",
            old_name="purchases_p_transac_3d55bc_idx",
        ),
        migrations.RenameIndex(
            model_name="purchasetransaction",
            new_name="purchase_pu_transac_eaa8ee_idx",
            old_name="purchases_p_transac_6fac49_idx",
        ),
        migrations.RenameIndex(
            model_name="purchasetransaction",
            new_name="purchase_pu_referen_26a524_idx",
            old_name="purchases_p_referen_b539d7_idx",
        ),
        migrations.RenameIndex(
            model_name="purchasetransaction",
            new_name="purchase_pu_invoice_0e0250_idx",
            old_name="purchases_p_invoice_8d604f_idx",
        ),
        migrations.RenameIndex(
            model_name="purchasetransactionitem",
            new_name="purchase_pu_serial__506678_idx",
            old_name="purchases_p_serial__0416f1_idx",
        ),
        migrations.RenameIndex(
            model_name="purchasetransactionitem",
            new_name="purchase_pu_referen_096fb1_idx",
            old_name="purchases_p_referen_58bcc0_idx",
        ),
        migrations.AlterField(
            model_name="purchasetransactionitem",
            name="inventory_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transaction_line_items",
                to="inventory_item.lineitem",
            ),
        ),
    ]
