# Generated by Django 4.2.17 on 2025-06-26 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('abbreviation', models.CharField(max_length=9, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Item Categories',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemSubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('abbreviation', models.CharField(max_length=9, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='item_category.itemcategory')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='item_catego_name_2c2ee5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='itemsubcategory',
            constraint=models.UniqueConstraint(fields=('name', 'item_category'), name='unique_subcategory_name_per_category'),
        ),
        migrations.AddIndex(
            model_name='itemcategory',
            index=models.Index(fields=['name'], name='item_catego_name_bd4fee_idx'),
        ),
    ]
