# Generated by Django 5.2.3 on 2025-06-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_item", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryItem',
            new_name='LineItem',
        ),
    ]
