# Generated by Django 5.2.3 on 2025-06-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_item", "0002_rename_inventoryitem_to_lineitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lineitem",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Line Item",
                "verbose_name_plural": "Line Items",
            },
        ),
        migrations.RenameIndex(
            model_name="lineitem",
            new_name="inventory_i_status_d5175d_idx",
            old_name="inventory_i_status_931a62_idx",
        ),
        migrations.RenameIndex(
            model_name="lineitem",
            new_name="inventory_i_serial__0f76d5_idx",
            old_name="inventory_i_serial__3ff198_idx",
        ),
        migrations.RenameIndex(
            model_name="lineitem",
            new_name="inventory_i_rentabl_496f53_idx",
            old_name="inventory_i_rentabl_56f0e1_idx",
        ),
    ]
